language: php
sudo: false
php:
  - 5.6
cache:
  apt: true
  directories:
    - $HOME/.rvm
    - $HOME/.buildcache
    - $HOME/.composer
    - $HOME/.drush/cache
branches:
  only:
    - 8.x

env:
  global:
    # The Acquia site name, as used in drush aliases.
    - ACQUIA_PROJECT=loriflame
    # The Drupal profile name.
    - PROFILE=loriflame
    - INSTALL_PROFILE=$HOME/build/$TRAVIS_REPO_SLUG
    - BUILD_SCRIPTS=$HOME/build/$TRAVIS_REPO_SLUG/tmp/travis_scripts
    - BUILD_CACHE=$HOME/.buildcache
    - BUILD_DB=$TRAVIS_REPO_SLUG.sql
    - BUILD_TEST=$HOME/build/loriflame
    - BUILD_DEPLOY=$HOME/build/loriflame_deploy
    # The Acquia git repository to deploy built commits to.
    - DEPLOY_REPO=loriflame1@svn-4934.devcloud.hosting.acquia.com:loriflame.git
    - DEPLOY_DEST=$HOME/loriflame
    - DEPLOY_BRANCH=develop
services:
  - memcached
  - mysql
addons:
  ssh_known_hosts:
    - srv-4939.devcloud.hosting.acquia.com
    - svn-4934.devcloud.hosting.acquia.com
    - 50.19.9.176
  hosts:
    - default
    - loriflame.local
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer global require drush/drush:8.0.*
  - mysql -e "CREATE DATABASE IF NOT EXISTS $PROFILE;"
  - cd $INSTALL_PROFILE
install: $BUILD_SCRIPTS/install.sh
before_script:
  - cd $BUILD_TEST
script: $BUILD_SCRIPTS/test.sh
after_success: $INSTALL_PROFILE/tmp/travis_scripts/deploy.sh
after_failure:
  - cat /var/log/apache2/error.log
  - cat /var/log/apache2/access.log
  - cat $HOME/php/error.log
  - php -i | grep memory
  - grep -i memory_limit ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
notifications:
  email:
    recipients:
      - oleksii.semko@gmail.com
    on_success: change
    on_failure: always
